"""
Copyright (c) 2020-2023, NVIDIA CORPORATION. All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto. Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
"""

cc_test(
    name = "test_entity",
    srcs = ["test_entity.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_query",
    srcs = ["test_query.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
        "//gxf/test/extensions:test",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetInt64",
    srcs = ["test_gxf_core_GxfParameterGetInt64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetUInt64",
    srcs = ["test_gxf_core_GxfParameterGetUInt64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetFloat64",
    srcs = ["test_gxf_core_GxfParameterGetFloat64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetFloat32",
    srcs = ["test_gxf_core_GxfParameterGetFloat32.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetAsYamlNode",
    srcs = ["test_gxf_core_GxfParameterGetAsYamlNode.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetBool",
    srcs = ["test_gxf_core_GxfParameterSetBool.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetHandle",
    srcs = ["test_gxf_core_GxfParameterSetHandle.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_GxfRegisterComponent",
    srcs = ["test_GxfRegisterComponent.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetStr",
    srcs = ["test_gxf_core_GxfParameterSetStr.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetUInt64",
    srcs = ["test_gxf_core_GxfParameterSetUInt64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetInt64",
    srcs = ["test_gxf_core_GxfParameterSetInt64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetFloat64",
    srcs = ["test_gxf_core_GxfParameterSetFloat64.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetFloat32",
    srcs = ["test_gxf_core_GxfParameterSetFloat32.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetInt32",
    srcs = ["test_gxf_core_GxfParameterSetInt32.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet1DInt32Vector",
    srcs = ["test_gxf_core_GxfParameterSet1DInt32Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet1DInt64Vector",
    srcs = ["test_gxf_core_GxfParameterSet1DInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet1DUInt64Vector",
    srcs = ["test_gxf_core_GxfParameterSet1DUInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet2DUInt64Vector",
    srcs = ["test_gxf_core_GxfParameterSet2DUInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet2DInt64Vector",
    srcs = ["test_gxf_core_GxfParameterSet2DInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet2DFloat64Vector",
    srcs = ["test_gxf_core_GxfParameterSet2DFloat64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet1DFloat64Vector",
    srcs = ["test_gxf_core_GxfParameterSet1DFloat64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSet2DInt32Vector",
    srcs = ["test_gxf_core_GxfParameterSet2DInt32Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DFloat64Vector",
    srcs = ["test_api_GxfParameterGet2DFloat64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DInt32Vector",
    srcs = ["test_api_GxfParameterGet2DInt32Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DUInt64Vector",
    srcs = ["test_api_GxfParameterGet2DUInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DInt64Vector",
    srcs = ["test_api_GxfParameterGet2DInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DInt32VectorInfo",
    srcs = ["test_api_GxfParameterGet2DInt32VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DUInt64VectorInfo",
    srcs = ["test_api_GxfParameterGet2DUInt64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DInt64VectorInfo",
    srcs = ["test_api_GxfParameterGet2DInt64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DInt32Vector",
    srcs = ["test_api_GxfParameterGet1DInt32Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DUInt64Vector",
    srcs = ["test_api_GxfParameterGet1DUInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DInt64Vector",
    srcs = ["test_api_GxfParameterGet1DInt64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DFloat64Vector",
    srcs = ["test_api_GxfParameterGet1DFloat64Vector.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DUInt32VectorInfo",
    srcs = ["test_api_GxfParameterGet1DInt32VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DUInt64VectorInfo",
    srcs = ["test_api_GxfParameterGet1DUInt64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DInt64VectorInfo",
    srcs = ["test_api_GxfParameterGet1DInt64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet1DFloat64VectorInfo",
    srcs = ["test_api_GxfParameterGet1DFloat64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_api_GxfParameterGet2DFloat64VectorInfo",
    srcs = ["test_api_GxfParameterGet2DFloat64VectorInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

"Making this test manual because this test is Flaky"

cc_test(
    name = "test_gxf_core_GxfEntityActivate",
    srcs = ["test_gxf_core_GxfEntityActivate.cpp"],
    data = [
        "test_ping_dynamic_activation.yaml",
        "//gxf/gxe:manifest",
    ],
    tags = ["manual"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityDeactivate",
    srcs = ["test_gxf_core_GxfEntityDeactivate.cpp"],
    data = [
        "test_ping_dynamic_activation.yaml",
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityDestroy",
    srcs = ["test_gxf_core_GxfEntityDestroy.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityFind",
    srcs = ["test_gxf_core_GxfEntityFind.cpp"],
    data = [
        "test_ping_dynamic_activation.yaml",
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityFindAll",
    srcs = ["test_gxf_core_GxfEntityFindAll.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityGetStatus",
    srcs = ["test_gxf_core_GxfEntityGetStatus.cpp"],
    data = [
        "test_ping_dynamic_activation.yaml",
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterInfo",
    srcs = ["test_gxf_core_GxfParameterInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphLoadFile",
    srcs = ["test_gxf_core_GxfGraphLoadFile.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphParseString",
    srcs = ["test_gxf_core_GxfGraphParseString.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfRuntimeInfo",
    srcs = ["test_gxf_core_GxfRuntimeInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/core/tests/test_extension:libgxf_test_extension.so",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterTypeStr",
    srcs = ["test_gxf_core_GxfParameterTypeStr.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGetParameterInfo",
    srcs = ["test_gxf_core_GxfGetParameterInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterFlagTypeStr",
    srcs = ["test_gxf_core_GxfParameterFlagTypeStr.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfRedirectLog",
    srcs = ["test_gxf_core_GxfRedirectLog.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphActivate",
    srcs = ["test_gxf_core_GxfGraphActivate.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphDeactivate",
    srcs = ["test_gxf_core_GxfGraphDeactivate.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/std",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphWait",
    srcs = ["test_gxf_core_GxfGraphWait.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/std",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphInterrupt",
    srcs = ["test_gxf_core_GxfGraphInterrupt.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/sample",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/std",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphRun",
    srcs = ["test_gxf_core_GxfGraphRun.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/std",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentInfo",
    srcs = ["test_gxf_core_GxfComponentInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfExtensionInfo",
    srcs = ["test_gxf_core_GxfExtensionInfo.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfContextCreate",
    srcs = ["test_gxf_core_GxfContextCreate.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfContextDestroy",
    srcs = ["test_gxf_core_GxfContextDestroy.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentName",
    srcs = ["test_gxf_core_GxfComponentName.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentEntity",
    srcs = ["test_gxf_core_GxfComponentEntity.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentAdd",
    srcs = ["test_gxf_core_GxfComponentAdd.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentFind",
    srcs = ["test_gxf_core_GxfComponentFind.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentType",
    srcs = ["test_gxf_core_GxfComponentType.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentPointer",
    srcs = ["test_gxf_core_GxfComponentPointer.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetStr",
    srcs = ["test_gxf_core_GxfParameterGetStr.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetHandle",
    srcs = ["test_gxf_core_GxfParameterGetHandle.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetBool",
    srcs = ["test_gxf_core_GxfParameterGetBool.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterGetInt32",
    srcs = ["test_gxf_core_GxfParameterGetInt32.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentTypeName",
    srcs = ["test_gxf_core_GxfComponentTypeName.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentTypeId",
    srcs = ["test_gxf_core_GxfComponentTypeId.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfComponentAddToInterface",
    srcs = ["test_gxf_core_GxfComponentAddToInterface.cpp"],
    data = [
        "test_app_GxfComponentAddToInterface.yaml",
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfGraphSetRootPath",
    srcs = ["test_gxf_core_GxfGraphSetRootPath.cpp"],
    data = [
        "//gxf/core/tests/apps:yaml_files",
        "//gxf/gxe:manifest",
        "//gxf/std",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_GxfLoadExtensionMetadataFiles",
    srcs = ["test_GxfLoadExtensionMetadataFiles.cpp"],
    data = [
        "//gxf/core/tests:metadata_files",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfCreateEntity",
    srcs = ["test_gxf_core_GxfCreateEntity.cpp"],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfUpdateEntityGroup",
    srcs = ["test_gxf_core_GxfUpdateEntityGroup.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfCreateEntityGroup",
    srcs = ["test_gxf_core_GxfCreateEntityGroup.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfParameterSetFromYaml",
    srcs = ["test_gxf_core_GxfParameterSetFromYaml.cpp"],
    data = [
        "//gxf/gxe:manifest",
        "//gxf/std",
        "//gxf/test/extensions:test",
    ],
    deps = [
        "//gxf/core:gxf",
        "//gxf/test/extensions:test",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_expected",
    srcs = ["test_expected.cpp"],
    data = [
        "//gxf/std:libgxf_std.so",
    ],
    deps = [
        "//gxf/core:expected",
        "//gxf/core:gxf",
        "//gxf/std:tensor",
        "@gtest//:main",
    ],
)
cc_test(
    name = "test_gxf_core_GxfEntityRefCountInc",
    srcs = ["test_gxf_core_GxfEntityRefCountInc.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

cc_test(
    name = "test_gxf_core_GxfEntityRefCountDec",
    srcs = ["test_gxf_core_GxfEntityRefCountDec.cpp"],
    data = [
        "//gxf/gxe:manifest",
    ],
    deps = [
        "//gxf/core:gxf",
        "@gtest//:main",
    ],
)

filegroup(
    name = "metadata_files",
    srcs = [
        "metadata.yaml",
        "metadata_component_not_list.yaml",
        "metadata_component_not_map.yaml",
        "metadata_invalid_type_id.yaml",
        "metadata_missing_base_typename.yaml",
        "metadata_missing_typeid.yaml",
        "metadata_missing_typename.yaml",
    ],
    visibility = ["//visibility:public"],
)
