"""
Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto. Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
"""

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\x03gxf\"*\n\x07Request\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x03(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2:\n\nServiceHub\x12,\n\x0bSendRequest\x12\x0c.gxf.Request\x1a\r.gxf.Response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:gxf.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:gxf.Response)
  })
_sym_db.RegisterMessage(Response)

_SERVICEHUB = DESCRIPTOR.services_by_name['ServiceHub']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=27
  _REQUEST._serialized_end=69
  _RESPONSE._serialized_start=71
  _RESPONSE._serialized_end=97
  _SERVICEHUB._serialized_start=99
  _SERVICEHUB._serialized_end=157
# @@protoc_insertion_point(module_scope)
